"""Add notifications

Revision ID: 20be8d66e9b8
Revises: b26c29439439
Create Date: 2026-07-13 00:34:42.137814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20be8d66e9b8'
down_revision: Union[str, None] = 'b26c29439439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('type', sa.Enum('TICKET_CREATED', 'TICKET_ASSIGNED', 'TICKET_REPLY', 'TICKET_UPDATED', 'TICKET_WAITING_CUSTOMER', 'TICKET_RESOLVED', 'TICKET_CLOSED', 'SYSTEM', name='notification_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'READ', 'ARCHIVED', name='notification_status_enum'), nullable=False),
    sa.Column('metadata_obj', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_ticket_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['related_ticket_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
