"""Add tenant model and tenant_id

Revision ID: 53cd456bcac5
Revises: b0f2b1016e5b
Create Date: 2026-07-19 00:59:45.574287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53cd456bcac5'
down_revision: Union[str, None] = 'b0f2b1016e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'TRIAL', 'ARCHIVED', name='tenantstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.add_column('chat_messages', sa.Column('tenant_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_chat_messages_tenant_id'), 'chat_messages', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'chat_messages', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('chat_sessions', sa.Column('tenant_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_chat_sessions_tenant_id'), 'chat_sessions', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'chat_sessions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('documents', sa.Column('tenant_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('improvement_recommendations', sa.Column('tenant_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_improvement_recommendations_tenant_id'), 'improvement_recommendations', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'improvement_recommendations', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('knowledge_gaps', sa.Column('tenant_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_knowledge_gaps_tenant_id'), 'knowledge_gaps', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'knowledge_gaps', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('knowledge_review_tasks', sa.Column('tenant_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_knowledge_review_tasks_tenant_id'), 'knowledge_review_tasks', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'knowledge_review_tasks', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('message_sources', sa.Column('tenant_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_message_sources_tenant_id'), 'message_sources', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'message_sources', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('notifications', sa.Column('tenant_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('ticket_internal_notes', sa.Column('tenant_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_ticket_internal_notes_tenant_id'), 'ticket_internal_notes', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'ticket_internal_notes', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('ticket_messages', sa.Column('tenant_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_ticket_messages_tenant_id'), 'ticket_messages', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'ticket_messages', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('ticket_status_history', sa.Column('tenant_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_ticket_status_history_tenant_id'), 'ticket_status_history', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'ticket_status_history', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('tickets', sa.Column('tenant_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_tickets_tenant_id'), 'tickets', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'tickets', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('tenant_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    
    import uuid
    from datetime import datetime, timezone
    
    default_tenant_id = str(uuid.uuid4())
    # Insert default tenant
    op.execute(
        f"INSERT INTO tenants (id, name, slug, status, created_at, updated_at) "
        f"VALUES ('{default_tenant_id}', 'Default Organization', 'default-org', 'ACTIVE', '{datetime.now(timezone.utc)}', '{datetime.now(timezone.utc)}')"
    )
    
    op.execute(f"UPDATE chat_messages SET tenant_id = '{default_tenant_id}' WHERE tenant_id IS NULL")
    op.alter_column('chat_messages', 'tenant_id', existing_type=sa.Uuid(), nullable=False)
    op.execute(f"UPDATE chat_sessions SET tenant_id = '{default_tenant_id}' WHERE tenant_id IS NULL")
    op.alter_column('chat_sessions', 'tenant_id', existing_type=sa.Uuid(), nullable=False)
    op.execute(f"UPDATE documents SET tenant_id = '{default_tenant_id}' WHERE tenant_id IS NULL")
    op.alter_column('documents', 'tenant_id', existing_type=sa.Uuid(), nullable=False)
    op.execute(f"UPDATE improvement_recommendations SET tenant_id = '{default_tenant_id}' WHERE tenant_id IS NULL")
    op.alter_column('improvement_recommendations', 'tenant_id', existing_type=sa.Uuid(), nullable=False)
    op.execute(f"UPDATE knowledge_gaps SET tenant_id = '{default_tenant_id}' WHERE tenant_id IS NULL")
    op.alter_column('knowledge_gaps', 'tenant_id', existing_type=sa.Uuid(), nullable=False)
    op.execute(f"UPDATE knowledge_review_tasks SET tenant_id = '{default_tenant_id}' WHERE tenant_id IS NULL")
    op.alter_column('knowledge_review_tasks', 'tenant_id', existing_type=sa.Uuid(), nullable=False)
    op.execute(f"UPDATE message_sources SET tenant_id = '{default_tenant_id}' WHERE tenant_id IS NULL")
    op.alter_column('message_sources', 'tenant_id', existing_type=sa.Uuid(), nullable=False)
    op.execute(f"UPDATE notifications SET tenant_id = '{default_tenant_id}' WHERE tenant_id IS NULL")
    op.alter_column('notifications', 'tenant_id', existing_type=sa.Uuid(), nullable=False)
    op.execute(f"UPDATE ticket_internal_notes SET tenant_id = '{default_tenant_id}' WHERE tenant_id IS NULL")
    op.alter_column('ticket_internal_notes', 'tenant_id', existing_type=sa.Uuid(), nullable=False)
    op.execute(f"UPDATE ticket_messages SET tenant_id = '{default_tenant_id}' WHERE tenant_id IS NULL")
    op.alter_column('ticket_messages', 'tenant_id', existing_type=sa.Uuid(), nullable=False)
    op.execute(f"UPDATE ticket_status_history SET tenant_id = '{default_tenant_id}' WHERE tenant_id IS NULL")
    op.alter_column('ticket_status_history', 'tenant_id', existing_type=sa.Uuid(), nullable=False)
    op.execute(f"UPDATE tickets SET tenant_id = '{default_tenant_id}' WHERE tenant_id IS NULL")
    op.alter_column('tickets', 'tenant_id', existing_type=sa.Uuid(), nullable=False)
    op.execute(f"UPDATE users SET tenant_id = '{default_tenant_id}' WHERE tenant_id IS NULL")
    op.alter_column('users', 'tenant_id', existing_type=sa.Uuid(), nullable=False)
# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_column('users', 'tenant_id')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_index(op.f('ix_tickets_tenant_id'), table_name='tickets')
    op.drop_column('tickets', 'tenant_id')
    op.drop_constraint(None, 'ticket_status_history', type_='foreignkey')
    op.drop_index(op.f('ix_ticket_status_history_tenant_id'), table_name='ticket_status_history')
    op.drop_column('ticket_status_history', 'tenant_id')
    op.drop_constraint(None, 'ticket_messages', type_='foreignkey')
    op.drop_index(op.f('ix_ticket_messages_tenant_id'), table_name='ticket_messages')
    op.drop_column('ticket_messages', 'tenant_id')
    op.drop_constraint(None, 'ticket_internal_notes', type_='foreignkey')
    op.drop_index(op.f('ix_ticket_internal_notes_tenant_id'), table_name='ticket_internal_notes')
    op.drop_column('ticket_internal_notes', 'tenant_id')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_column('notifications', 'tenant_id')
    op.drop_constraint(None, 'message_sources', type_='foreignkey')
    op.drop_index(op.f('ix_message_sources_tenant_id'), table_name='message_sources')
    op.drop_column('message_sources', 'tenant_id')
    op.drop_constraint(None, 'knowledge_review_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_review_tasks_tenant_id'), table_name='knowledge_review_tasks')
    op.drop_column('knowledge_review_tasks', 'tenant_id')
    op.drop_constraint(None, 'knowledge_gaps', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_gaps_tenant_id'), table_name='knowledge_gaps')
    op.drop_column('knowledge_gaps', 'tenant_id')
    op.drop_constraint(None, 'improvement_recommendations', type_='foreignkey')
    op.drop_index(op.f('ix_improvement_recommendations_tenant_id'), table_name='improvement_recommendations')
    op.drop_column('improvement_recommendations', 'tenant_id')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_column('documents', 'tenant_id')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_chat_sessions_tenant_id'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'tenant_id')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_index(op.f('ix_chat_messages_tenant_id'), table_name='chat_messages')
    op.drop_column('chat_messages', 'tenant_id')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
