"""add_sla_fields_to_tickets

Revision ID: 6e952b9abc61
Revises: c26a957d309c
Create Date: 2026-07-18 23:57:49.058814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e952b9abc61'
down_revision: Union[str, None] = 'c26a957d309c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('first_response_due', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('resolution_due', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('first_response_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tickets_first_response_due'), 'tickets', ['first_response_due'], unique=False)
    op.create_index(op.f('ix_tickets_resolution_due'), 'tickets', ['resolution_due'], unique=False)
    
    # Add new enum values to Postgres
    connection = op.get_bind()
    if connection.dialect.name == 'postgresql':
        op.execute("ALTER TYPE tickethistoryevent ADD VALUE IF NOT EXISTS 'SLA_BREACHED'")
        op.execute("ALTER TYPE tickethistoryevent ADD VALUE IF NOT EXISTS 'FIRST_RESPONSE_RECORDED'")
        op.execute("ALTER TYPE tickethistoryevent ADD VALUE IF NOT EXISTS 'TICKET_RESOLVED_WITHIN_SLA'")
        op.execute("ALTER TYPE tickethistoryevent ADD VALUE IF NOT EXISTS 'TICKET_RESOLVED_AFTER_SLA'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_resolution_due'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_first_response_due'), table_name='tickets')
    op.drop_column('tickets', 'first_response_at')
    op.drop_column('tickets', 'resolution_due')
    op.drop_column('tickets', 'first_response_due')
    # ### end Alembic commands ###
