"""add assigned_at to tickets

Revision ID: 6f6971df89ef
Revises: 20be8d66e9b8
Create Date: 2026-07-18 23:12:52.023121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f6971df89ef'
down_revision: Union[str, None] = '20be8d66e9b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'assigned_at')
    # ### end Alembic commands ###
