"""Add knowledge_sources to tickets

Revision ID: 86c51a8bbb6a
Revises: 0aceae779f66
Create Date: 2026-07-19 17:06:05.014639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c51a8bbb6a'
down_revision: Union[str, None] = '0aceae779f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('knowledge_sources', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'knowledge_sources')
    # ### end Alembic commands ###
