"""Add ImprovementRecommendation

Revision ID: 89e64c072d34
Revises: b58fa2386f77
Create Date: 2026-07-19 00:38:17.769405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e64c072d34'
down_revision: Union[str, None] = 'b58fa2386f77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('improvement_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_gap_id', sa.UUID(), nullable=True),
    sa.Column('recommendation_type', sa.Enum('DOCUMENT_REVIEW', 'CONTENT_EXPANSION', 'CONTENT_UPDATE', 'KNOWLEDGE_GAP', 'RETRIEVAL_OPTIMIZATION', 'CHUNK_REVIEW', name='recommendationtype'), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'DISMISSED', name='recommendationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_gap_id'], ['knowledge_gaps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_improvement_recommendations_document_id'), 'improvement_recommendations', ['document_id'], unique=False)
    op.create_index(op.f('ix_improvement_recommendations_knowledge_gap_id'), 'improvement_recommendations', ['knowledge_gap_id'], unique=False)
    op.create_index(op.f('ix_improvement_recommendations_recommendation_type'), 'improvement_recommendations', ['recommendation_type'], unique=False)
    op.create_index(op.f('ix_improvement_recommendations_status'), 'improvement_recommendations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_improvement_recommendations_status'), table_name='improvement_recommendations')
    op.drop_index(op.f('ix_improvement_recommendations_recommendation_type'), table_name='improvement_recommendations')
    op.drop_index(op.f('ix_improvement_recommendations_knowledge_gap_id'), table_name='improvement_recommendations')
    op.drop_index(op.f('ix_improvement_recommendations_document_id'), table_name='improvement_recommendations')
    op.drop_table('improvement_recommendations')
    # ### end Alembic commands ###
