"""Add KnowledgeReviewTask

Revision ID: b0f2b1016e5b
Revises: 89e64c072d34
Create Date: 2026-07-19 00:45:18.641865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f2b1016e5b'
down_revision: Union[str, None] = '89e64c072d34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_review_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('assigned_admin_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'UNDER_REVIEW', 'COMPLETED', 'DISMISSED', name='reviewtaskstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['improvement_recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_review_tasks_assigned_admin_id'), 'knowledge_review_tasks', ['assigned_admin_id'], unique=False)
    op.create_index(op.f('ix_knowledge_review_tasks_document_id'), 'knowledge_review_tasks', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_review_tasks_recommendation_id'), 'knowledge_review_tasks', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_knowledge_review_tasks_status'), 'knowledge_review_tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_review_tasks_status'), table_name='knowledge_review_tasks')
    op.drop_index(op.f('ix_knowledge_review_tasks_recommendation_id'), table_name='knowledge_review_tasks')
    op.drop_index(op.f('ix_knowledge_review_tasks_document_id'), table_name='knowledge_review_tasks')
    op.drop_index(op.f('ix_knowledge_review_tasks_assigned_admin_id'), table_name='knowledge_review_tasks')
    op.drop_table('knowledge_review_tasks')
    # ### end Alembic commands ###
