"""Add KnowledgeGap

Revision ID: b58fa2386f77
Revises: d3268bcc3ac9
Create Date: 2026-07-19 00:35:01.460330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b58fa2386f77'
down_revision: Union[str, None] = 'd3268bcc3ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_gaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('gap_type', sa.Enum('HIGH_FLAG_RATE', 'LOW_HEALTH_SCORE', 'REPEATED_FAILURES', 'MISSING_KNOWLEDGE', 'OUTDATED_CONTENT', name='gaptype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='gapseverity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_gaps_document_id'), 'knowledge_gaps', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_gaps_gap_type'), 'knowledge_gaps', ['gap_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_gaps_gap_type'), table_name='knowledge_gaps')
    op.drop_index(op.f('ix_knowledge_gaps_document_id'), table_name='knowledge_gaps')
    op.drop_table('knowledge_gaps')
    # ### end Alembic commands ###
