"""Add message_sources table

Revision ID: d3268bcc3ac9
Revises: 6e952b9abc61
Create Date: 2026-07-19 00:10:41.818193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3268bcc3ac9'
down_revision: Union[str, None] = '6e952b9abc61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_message_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('retrieval_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_sources_chat_message_id'), 'message_sources', ['chat_message_id'], unique=False)
    op.create_index(op.f('ix_message_sources_created_at'), 'message_sources', ['created_at'], unique=False)
    op.create_index(op.f('ix_message_sources_document_id'), 'message_sources', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_sources_document_id'), table_name='message_sources')
    op.drop_index(op.f('ix_message_sources_created_at'), table_name='message_sources')
    op.drop_index(op.f('ix_message_sources_chat_message_id'), table_name='message_sources')
    op.drop_table('message_sources')
    # ### end Alembic commands ###
