from pydantic import BaseModel, Field
from typing import List, Optional


from app.core.config import settings

class ChatRequest(BaseModel):
    message: str = Field(
        ...,
        max_length=settings.MAX_MESSAGE_LENGTH,
        description="The message from the user"
    )
    regenerate: bool = Field(
        default=False,
        description="Whether to regenerate the last assistant response"
    )


class SourceCitation(BaseModel):
    filename: str
    retrieval_score: Optional[float] = None


class ChatResponse(BaseModel):
    answer: str = Field(..., description="The answer generated by the assistant")
    sources: List[SourceCitation] = Field(
        default_factory=list, description="Source documents used for generation"
    )

class FeedbackRequest(BaseModel):
    feedback: str = Field(..., description="The feedback to submit, either 'like' or 'dislike'")

class FlagRequest(BaseModel):
    reason: str = Field(..., description="Reason for flagging the message")
    comment: Optional[str] = Field(None, description="Optional comment from the user")
